Models/Classroom.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public Classroom()
        {
            this.Evaluations = new HashSet<Evaluation>();
            this.Pupils = new HashSet<Pupil>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public System.Guid User_Id { get; set; }
        public System.Guid Year_Id { get; set; }
        public System.Guid Establishment_Id { get; set; }
    
        public virtual Establishment Establishment { get; set; }
        public virtual User User { get; set; }
        public virtual Year Year { get; set; }
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<Pupil> Pupils { get; set; }
    }
}

Areas/ClassManagement/Controllers/ClassroomController.cs
using SchoolManager.Areas.ClassManagement.Models;
using SchoolManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManager.Areas.ClassManagement.Controllers
{
    public class ClassroomController : Controller
    {
        private void setViewData() {
            using (Entities entity = new Entities())
            {
                YearRepository yearRepo = new YearRepository(entity);
                EstablishmentRepository establishmentRepo = new EstablishmentRepository(entity);
                UserRepository userRepo = new UserRepository(entity);
                Dictionary<EstablishmentModel, UserModel> establishmentManager = new Dictionary<EstablishmentModel, UserModel>();
                var establishments = establishmentRepo.All().Select(u => new EstablishmentModel
                {
                    id = u.Id,
                    Name = u.Name,
                    User_Id = u.User_Id
                }).ToList();
                foreach (EstablishmentModel establishment in establishments)
                {
                    UserModel user = userRepo.getById(establishment.User_Id).Select(u => new UserModel
                    {
                        FirstName = u.FirstName,
                        LastName = u.LastName,
                        Id = u.Id
                    }).First();
                    establishmentManager[establishment] = user;
                }
                ViewData["establishmentManager"] = establishmentManager;
                ViewData["years"] = yearRepo.All().Select(y => new YearModel
                {
                    Id = y.Id,
                    Year1 = y.Year1
                }).ToList();
            }
        }

        public void convertClassroomModelToClassroom(ClassroomModel classroom, Classroom c)
        {
            c.Id = classroom.Id;
            c.Establishment_Id = classroom.Establishment_Id;
            c.Title = classroom.Title;
            c.Year_Id = classroom.Year_Id;
            c.User_Id = classroom.User_Id;
        }

        public ActionResult Index()
        {
            using (var entity = new Entities())
            {
                var repo = new ClassroomRepository(entity);
                var establishmentRepo = new EstablishmentRepository(entity);
                var yearRepo = new YearRepository(entity);
                var userRepo = new UserRepository(entity);
                List<ClassroomModel> classrooms = repo.All().Select(c => new ClassroomModel
                {
                    Id = c.Id,
                    Title = c.Title,
                    User_Id = c.User_Id,
                    Year_Id = c.Year_Id,
                    Establishment_Id = c.Establishment_Id,
                    Establishment_Name = c.Establishment.Name,
                    Year1 = c.Year.Year1,
                    User_Name = c.User.FirstName + " " + c.User.LastName,
                }).ToList();
                return View(classrooms);
            };
        }

        [HttpGet]
        public ActionResult Create(Guid? Year_Id, Guid? Establishment_Id)
        {
            using (var entity = new Entities())
            {
                ClassroomModel classroom = new ClassroomModel();
                if (Year_Id.HasValue)
                {
                    classroom.Year_Id = (Guid) Year_Id;
                }
                if (Establishment_Id.HasValue)
                {
                    classroom.Establishment_Id = (Guid)Establishment_Id;
                }
                // Add all the data about establishment and year in the view data.
                setViewData();
                
                return View(classroom);
            }
        }

        [HttpPost]
        public ActionResult Create(ClassroomModel classroom)
        {
            if (ModelState.IsValid)
            {
                using (var entity = new Entities())
                {
                    ClassroomRepository repo = new ClassroomRepository(entity);
                    EstablishmentRepository establishmentRepo = new EstablishmentRepository(entity);
                    UserRepository userRepo = new UserRepository(entity);
                    classroom.User_Id = establishmentRepo.getById(classroom.Establishment_Id).First().User_Id;
                    classroom.Establishment_Name = establishmentRepo.getById(classroom.Establishment_Id).First().Name;
                    classroom.pupils = new List<PupilModel>();
                    classroom.evaluations = new List<EvaluationModel>();
                    classroom.User_Name = userRepo.getById(classroom.User_Id).First().FirstName + " " + userRepo.getById(classroom.User_Id).First().LastName;
                    classroom.Id = Guid.NewGuid();
                    Classroom c = new Classroom();
                    convertClassroomModelToClassroom(classroom, c);
                    repo.Add(c);
                    repo.Save();
                    return View("~/Areas/ClassManagement/Views/Classroom/Read.cshtml", classroom);
                }

            }
            setViewData();
            return View(classroom);
        }

        [HttpGet]
        public ActionResult Read(Guid id)
        {
            using (var entity = new Entities())
            {
                ClassroomRepository repo = new ClassroomRepository(entity);
                PupilRepository pupilRepo = new PupilRepository(entity);
                EvaluationRepository evaluationRepo = new EvaluationRepository(entity);
                ClassroomModel classroom = repo.getById(id).Select(c => new ClassroomModel
                {
                    Id = c.Id,
                    Title = c.Title,
                    User_Id = c.User_Id,
                    Year_Id = c.Year_Id,
                    Establishment_Id = c.Establishment_Id,
                    Establishment_Name = c.Establishment.Name,
                    Year1 = c.Year.Year1,
                    User_Name = c.User.FirstName + " " + c.User.LastName,
                }).First();
                classroom.pupils = pupilRepo.getByClassroom(id).Select(p => new PupilModel{
                    Id = p.Id,
                    FirstName = p.FirstName,
                    LastName = p.LastName,
                    Sex = p.Sex,
                    BirthdayDate = p.BirthdayDate,
                    State = p.State,
                    Tutor_Id = p.Tutor_Id,
                    TutorName = p.Tutor.FirstName + " " + p.Tutor.LastName,
                    Classroom_Id = p.Classroom_Id,
                    ClassroomTitle = p.Classroom.Title,
                    Level_Id = p.Level_Id,
                    LevelTitle = p.Level.Title
                }).ToList();
                classroom.evaluations = evaluationRepo.getByClassroom(id).Select(e => new EvaluationModel
                {
                    Id = e.Id,
                    Classroom_Id = e.Classroom_Id,
                    User_Id = e.User_Id,
                    Period_Id = e.Period_Id,
                    Date = e.Date,
                    TotalPoint = e.TotalPoint
                }).ToList();
                return View(classroom);
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            using (var entity = new Entities())
            {
                ClassroomRepository repo = new ClassroomRepository(entity);
                ClassroomModel classroom = repo.getById(id).Select(c => new ClassroomModel
                {
                    Id = c.Id,
                    Establishment_Id = c.Establishment_Id,
                    Title = c.Title,
                    Year_Id = c.Year_Id,
                    User_Id = c.User_Id
                }).First();

                setViewData();
                return View("~/Areas/ClassManagement/Views/Classroom/Edit.cshtml", classroom);
            }
        }

        [HttpPost]
        public ActionResult Edit(ClassroomModel classroom)
        {
            if (ModelState.IsValid)
            {
                using (var entity = new Entities())
                {
                    ClassroomRepository repo = new ClassroomRepository(entity);
                    EstablishmentRepository establishmentRepo = new EstablishmentRepository(entity);
                    classroom.User_Id = establishmentRepo.getById(classroom.Establishment_Id).First().User_Id;
                    Classroom c = repo.getById(classroom.Id).First();
                    convertClassroomModelToClassroom(classroom, c);
                    repo.Save();
                }
                return RedirectToAction("Index");
            }
            setViewData();
            return View(classroom);
           
        }

        [HttpPost]
        public ActionResult Search(string query)
        {
            using (var entity = new Entities())
            {
                String[] results = query.Split(new Char[] { ' ', ',' });
                var repo = new ClassroomRepository(entity);
                var classrooms = repo.Search(results).Select(c => new ClassroomModel
                {
                    Id = c.Id,
                    Title = c.Title,
                    User_Id = c.User_Id,
                    Year_Id = c.Year_Id,
                    Establishment_Id = c.Establishment_Id,
                    Establishment_Name = c.Establishment.Name,
                    Year1 = c.Year.Year1,
                    User_Name = c.User.FirstName + " " + c.User.LastName,
                }).ToList();

                return PartialView("~/Areas/ClassManagement/Views/Shared/_ClassroomResults.cshtml", classrooms);
            }
        }
    }
}

Areas/ClassManagement/Views/Classroom/Create.cshtml
@model SchoolManager.Models.ClassroomModel
@{
    ViewBag.Title = "Create - Classroom";
    var establishmentDico = (Dictionary<SchoolManager.Areas.ClassManagement.Models.EstablishmentModel,
        SchoolManager.Areas.ClassManagement.Models.UserModel>) ViewData["establishmentManager"];
}

<h2>New Classroom</h2>
@{Html.BeginForm("Create", "Classroom", FormMethod.Post, new { @class="form-horizontal"});}
@Html.HiddenFor(t => t.Id)

<div class="form-group @if (!ViewData.ModelState.IsValidField("Title")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Title, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Title, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Title, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Establishment and teacher</label>
    <div class="col-sm-10">
        <select class="form-control" id="Establishment_Id" name="Establishment_Id">
            @foreach (var establishment in establishmentDico.Keys)
            {
                if (@establishment.id == @Model.Establishment_Id)
                {
                    <option selected="selected" value="@establishment.id">@establishment.Name with @establishmentDico[establishment].FirstName @establishmentDico[establishment].LastName</option>
                }
                else
                {
                    <option value="@establishment.id">@establishment.Name with @establishmentDico[establishment].FirstName @establishmentDico[establishment].LastName</option>
                }
            }
        </select>
    </div>
</div>

<div class="form-group">
    <label for="Year_Id" class="col-sm-2 control-label">Year</label>
    <div class="col-sm-10">
        <select class="form-control" id="Year_Id" name="Year_Id">
            @foreach (var year in (List<SchoolManager.Models.YearModel>)ViewData["years"])
            {
                if (@year.Id == Model.Year_Id)
                {
                    <option selected="selected" value="@year.Id">@year.Year1</option>
                }
                else
                {
                    <option value="@year.Id">@year.Year1</option>
                }
            }
        </select>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</div>
@{Html.EndForm();}

Areas/ClassManagement/Views/Classroom/Edit.cshtml
@model SchoolManager.Models.ClassroomModel
@{
    ViewBag.Title = "Create - Classroom";
    var establishmentDico = (Dictionary<SchoolManager.Areas.ClassManagement.Models.EstablishmentModel,
        SchoolManager.Areas.ClassManagement.Models.UserModel>)ViewData["establishmentManager"];
}

<h2>Edit Classroom</h2>
@{Html.BeginForm("Edit", "Classroom", FormMethod.Post, new { @class = "form-horizontal" });}
@Html.HiddenFor(t => t.Id)

<div class="form-group @if (!ViewData.ModelState.IsValidField("Title")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Title, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Title, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Title, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Establishment and teacher</label>
    <div class="col-sm-10">
        <select class="form-control" id="Establishment_Id" name="Establishment_Id">
            @foreach (var establishment in establishmentDico.Keys)
            {
                if (@establishment.id == @Model.Establishment_Id)
                {
                    <option selected="selected" value="@establishment.id">@establishment.Name with @establishmentDico[establishment].FirstName @establishmentDico[establishment].LastName</option>
                }
                else
                {
                    <option value="@establishment.id">@establishment.Name with @establishmentDico[establishment].FirstName @establishmentDico[establishment].LastName</option>
                }
            }
        </select>
    </div>
</div>

<div class="form-group">
    <label for="Year_Id" class="col-sm-2 control-label">Year</label>
    <div class="col-sm-10">
        <select class="form-control" id="Year_Id" name="Year_Id">
            @foreach (var year in (List<SchoolManager.Models.YearModel>)ViewData["years"])
            {
                if (@year.Id == Model.Year_Id)
                {
                    <option selected="selected" value="@year.Id">@year.Year1</option>
                }
                else
                {
                    <option value="@year.Id">@year.Year1</option>
                }
            }
        </select>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Edit" class="btn btn-primary" />
    </div>
</div>
@{Html.EndForm();}

Areas/ClassManagement/Views/Classroom/Index.cshtml
@model List<SchoolManager.Models.ClassroomModel>
    @{
        ViewBag.Title = "Index";
    }

    <h2>Classrooms</h2>
<div id="search">
    @using (Ajax.BeginForm("Search", "Classroom",
        new AjaxOptions
        {
            UpdateTargetId = "ClassroomsArray",
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
        }, new { @class = "form-group" }))
    {
        <div class="input-group">
            <input type="text" name="query" class="form-control" placeholder="Search..." />
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-search"></i>
            </span>
        </div>
    }
</div>
<div id="ClassroomsArray">
    @Html.Partial("~/Areas/ClassManagement/Views/Shared/_ClassroomResults.cshtml", @Model)
</div>

Areas/ClassManagement/Views/Classroom/Read.cshtml
@model SchoolManager.Models.ClassroomModel
@{
    ViewBag.Title = "Index";
}

<h2>Classroom @Model.Title</h2>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Teacher</th>
            <th>Establishment</th>
        </tr>
    </thead>
    <tbody>
        <tr>

            <td>@Model.Title</td>
            <td>
            @Html.ActionLink(
                linkText: Model.Year1.ToString(),
                actionName: "Read",
                controllerName: "Year",
                routeValues: new
                {
                    area = "Administration",
                    id = @Model.Year_Id
                },
                htmlAttributes: new
                {
                    @class = "",
                    target = "_blank",
                }
            )
        </td>
        <td>@Model.User_Name</td>
        <td>
            @Html.ActionLink(
                linkText: @Model.Establishment_Name,
                actionName: "Read",
                controllerName: "Establishment",
                routeValues: new
                    {
                        id = @Model.Establishment_Id
                    },
                htmlAttributes: new
                    {
                        target = "_blank",
                    }
            )
    </td>
    <td>
        @Html.ActionLink(
            linkText: "Edit",
            actionName: "Edit",
            controllerName: "Classroom",
            routeValues: new
                {
                    id = @Model.Id
                },
            htmlAttributes: new
                {
                    target = "_blank",
                }
        )
    </td>
    </tr>
    </tbody>
</table>
<h2>Pupils in @Model.Title</h2>
<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Sex</th>
            <th>Birthday Date</th>
            <th>Tutor</th>
            <th>Classroom</th>
            <th>Level</th>
            <th>
                @Html.ActionLink(
                    linkText: "Add Pupil",
                    actionName: "Create",
                    controllerName: "Pupil",
                    routeValues: new
                    {
                        Classroom_Id = Model.Id
                    },
                    htmlAttributes: new
                    {
                        @class = "btn btn-default",
                        target = "_blank",
                    }
                )
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pupil in Model.pupils)
        {
            <tr>
                <td>@pupil.FirstName</td>
                <td>@pupil.LastName</td>
                <td>@((SchoolManager.Models.PupilModel.Sexes)pupil.Sex)</td>
                <td>@pupil.BirthdayDate.ToShortDateString()</td>
                <td>
                    @Html.ActionLink(
                        linkText: pupil.TutorName,
                        actionName: "Read",
                        controllerName: "Tutor",
                        routeValues: new
                          {
                              id = @pupil.Tutor_Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: pupil.ClassroomTitle,
                        actionName: "Read",
                        controllerName: "Classroom",
                        routeValues: new
                          {
                              id = @pupil.Classroom_Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: pupil.LevelTitle,
                        actionName: "Read",
                        controllerName: "Level",
                        routeValues: new
                          {
                              area = "Administration",
                              id = @pupil.Level_Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: "See",
                        actionName: "Read",
                        controllerName: "Pupil",
                        routeValues: new
                          {
                              id = @pupil.Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: "Edit",
                        actionName: "Edit",
                        controllerName: "Pupil",
                        routeValues: new
                          {
                              id = @pupil.Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
            </tr>
        }
    </tbody>
</table>
<h2>Evaluations</h2>
<table class="table">
    <thead>
        <tr>
            <th>Date</th>
            <th>Point</th>
            <th>
                @Html.ActionLink(
                    linkText: "Add Evaluation",
                    actionName: "Create",
                    controllerName: "Evaluation",
                    routeValues: new
                    {
                        Classroom_Id = Model.Id
                    },
                    htmlAttributes: new
                    {
                        @class = "btn btn-default",
                        target = "_blank",
                    }
                )
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var eval in Model.evaluations)
        {
            <tr>
                <td>@eval.Date.ToShortDateString()</td>
                <td>@eval.TotalPoint</td>
                <td>
                    @Html.ActionLink(
                        linkText: "See",
                        actionName: "Read",
                        controllerName: "Evaluation",
                        routeValues: new
                          {
                                id = eval.Id
                          },
                          htmlAttributes: null
                    )
                </td>
            </tr>
        }
    </tbody>
</table>