Models/Tutor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        public Tutor()
        {
            this.Pupils = new HashSet<Pupil>();
        }
    
        public System.Guid Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public string Town { get; set; }
        public string Tel { get; set; }
        public string Mail { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Pupil> Pupils { get; set; }
    }
}

Areas/ClassManagement/Controllers/TutorController.cs
using SchoolManager.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManager.Areas.ClassManagement.Controllers
{
    public class TutorController : Controller
    {
        //
        // GET: /Tutor/

        public void convertTutorModelToTutor(TutorModel tutor, Tutor t)
        {
            t.Id = tutor.Id;
            t.LastName = tutor.LastName;
            t.Address = tutor.Address;
            t.FirstName = tutor.FirstName;
            t.Mail = tutor.Mail;
            t.PostCode = tutor.PostCode;
            t.Tel = tutor.Tel;
            t.Town = tutor.Town;
            t.Comment = tutor.Comment;
        }

        public ActionResult Index()
        {
            using (var entity = new Entities())
            {
                var repo = new TutorRepository(entity);
                List<TutorModel> tutors = repo.All().Select(s => new TutorModel
                {
                    Id = s.Id,
                    FirstName = s.FirstName,
                    LastName = s.LastName,
                    Address = s.Address,
                    PostCode = s.PostCode,
                    Town = s.Town,
                    Tel = s.Tel,
                    Mail = s.Mail,
                    Comment = s.Comment
                }).ToList();

                return View(tutors);
            };
        }
        public ActionResult Read(Guid id)
        {
            using (var entity = new Entities())
            {
                var pupilsRepo = new PupilRepository(entity);
                var tutorRepo = new TutorRepository(entity);
                TutorModel tutor = tutorRepo.getById(id).Select(t => new TutorModel
                {
                    Id = t.Id,
                    FirstName = t.FirstName,
                    LastName = t.LastName,
                    Address = t.Address,
                    PostCode = t.PostCode,
                    Town = t.Town,
                    Tel = t.Tel,
                    Mail = t.Mail,
                    Comment = t.Comment
                }).First();
                List<PupilModel> pupils = pupilsRepo.getByTutor(id).Select(p => new PupilModel
                {
                    BirthdayDate = p.BirthdayDate,
                    FirstName = p.FirstName,
                    LastName = p.LastName,
                    Sex = p.Sex,
                    State = p.State,
                    Level_Id = p.Level_Id,
                    LevelTitle = p.Level.Title,
                    Tutor_Id = tutor.Id,
                    TutorName = tutor.FirstName + " " + tutor.LastName,
                    ClassroomTitle = p.Classroom.Title,
                    Classroom_Id = p.Classroom_Id
                }).ToList();
                tutor.pupils = pupils;
                return View(tutor);
            }
        }
        
        [HttpGet]
        public ActionResult Create()
        {
            TutorModel tutor = new TutorModel();
            
            return View(tutor);
        }

        [HttpPost]
        public ActionResult Create(TutorModel tutor)
        {
            if (ModelState.IsValid)
            {
                using (var entity = new Entities()) {
                    TutorRepository repo = new TutorRepository(entity);
                    tutor.Id = Guid.NewGuid();
                    Tutor t = new Tutor();
                    convertTutorModelToTutor(tutor, t);
                    repo.Add(t);
                    repo.Save();
                    return RedirectToAction("Index");
                }

            }

                return View(tutor);
            
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            using (var entity = new Entities())
            {
                TutorRepository repo = new TutorRepository(entity);
                TutorModel tutor = repo.getById(id).Select(t => new TutorModel
                {
                    Id = t.Id,
                    Address = t.Address,
                    Comment = t.Comment,
                    FirstName = t.FirstName,
                    LastName = t.LastName,
                    Mail = t.Mail,
                    PostCode = t.PostCode,
                    Tel = t.Tel,
                    Town = t.Town,
                }).First();
                return View("~/Areas/ClassManagement/Views/Tutor/Edit.cshtml", tutor);
            }
        }

        [HttpPost]
        public ActionResult Edit(TutorModel tutor)
        {
            if (ModelState.IsValid)
            {
                using (var entity = new Entities())
                {
                    TutorRepository repo = new TutorRepository(entity);
                    Tutor t = repo.getById(tutor.Id).First();
                    convertTutorModelToTutor(tutor, t);
                    repo.Save();
                }
                return RedirectToAction("Read", new { id = tutor.Id });
            }
            return View(tutor);
            
        }

        [HttpPost]
        public ActionResult Search(string query)
        {
            using (var entity = new Entities())
            {
                String[] results = query.Split(new Char[] { ' ', ',' });
                var repo = new TutorRepository(entity);
                var tutors = repo.Search(results).Select(s => new TutorModel
                {
                    Id = s.Id,
                    FirstName = s.FirstName,
                    LastName = s.LastName,
                    Address = s.Address,
                    PostCode = s.PostCode,
                    Town = s.Town,
                    Tel = s.Tel,
                    Mail = s.Mail,
                    Comment = s.Comment
                }).ToList();

                return PartialView("~/Areas/ClassManagement/Views/Shared/_TutorResults.cshtml", tutors);
            }
        }
    }
}

Areas/ClassManagement/Views/Tutor/Create.cshtml
@model SchoolManager.Models.TutorModel
@{
    ViewBag.Title = "Create - Tutor";
}

<h2>Create Tutor</h2>

@{Html.BeginForm("Create", "Tutor", FormMethod.Post, new { @class = "form-horizontal" });}
@Html.HiddenFor(t => t.Id)

<div class="form-group @if (!ViewData.ModelState.IsValidField("FirstName")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.FirstName, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.FirstName, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.FirstName, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("LastName")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.LastName, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.LastName, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.LastName, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>


<div class="form-group @if (!ViewData.ModelState.IsValidField("Address")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Address, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Address, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Address, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("PostCode")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.PostCode, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.PostCode, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.PostCode, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("Town")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Town, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Town, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Town, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("Tel")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Tel, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Tel, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Tel, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("Mail")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Mail, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Mail, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Mail, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("Comment")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Comment, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Comment, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Comment, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</div>
@{Html.EndForm();}

Areas/ClassManagement/Views/Tutor/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

@model SchoolManager.Models.TutorModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Tutor</h2>

@{Html.BeginForm("Edit", "Tutor", FormMethod.Post, new { @class = "form-horizontal" });}
@Html.HiddenFor(t => t.Id)

<div class="form-group @if (!ViewData.ModelState.IsValidField("FirstName")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.FirstName, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.FirstName, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.FirstName, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("LastName")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.LastName, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.LastName, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.LastName, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>


<div class="form-group @if (!ViewData.ModelState.IsValidField("Address")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Address, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Address, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Address, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("PostCode")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.PostCode, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.PostCode, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.PostCode, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("Town")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Town, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Town, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Town, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("Tel")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Tel, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Tel, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Tel, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("Mail")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Mail, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Mail, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Mail, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>

<div class="form-group @if (!ViewData.ModelState.IsValidField("Comment")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Comment, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.Comment, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Comment, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Edit" class="btn btn-primary" />
    </div>
</div>
@{Html.EndForm();}

Areas/ClassManagement/Views/Tutor/Index.cshtml
@model List<SchoolManager.Models.TutorModel>
@{
    ViewBag.Title = "Tutors";
}

<h2>Tutors</h2>
 <div id="search">
    @using (Ajax.BeginForm("Search", "Tutor",
        new AjaxOptions
        {
            UpdateTargetId = "TutorsArray",
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
        }, new { @class = "form-group" }))
    {
        <div class="input-group">
            <input type="text" name="query" class="form-control" placeholder="Search..." />
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-search"></i>
            </span>
        </div>
    }
</div>
<div id="TutorsArray">
    @Html.Partial("~/Areas/ClassManagement/Views/Shared/_TutorResults.cshtml", @Model)
</div> 

Areas/ClassManagement/Views/Tutor/Read.cshtml
@model SchoolManager.Models.TutorModel
@{
    ViewBag.Title = "Read - Tutor";
}
<h2>Tutor @Model.FirstName @Model.LastName </h2>
<table class="table">
    <thead>
        <tr>
            <th>Address</th>
            <th>Post code</th>
            <th>Town</th>
            <th>Tel</th>
            <th>Mail</th>
            <th>Comment</th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td>@Model.Address</td>
                <td>@Model.PostCode</td>
                <td>@Model.Town</td>
                <th>@Model.Tel</th>
                <th>@Model.Mail</th>
                <th>@Model.Comment</th>
            </tr>
    </tbody>
</table>

<h2>Pupils</h2>
<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Sex</th>
            <th>Birthday Date</th>
            <th>Tutor</th>
            <th>Classroom</th>
            <th>Level</th>
            <th>
                @Html.ActionLink(
                    linkText: "Add Pupil",
                    actionName: "Create",
                    controllerName: "Pupil",
                    routeValues: new
                    {
                        Tutor_Id = Model.Id
                    },
                    htmlAttributes: new
                    {
                        @class = "btn btn-default",
                        target = "_blank",
                    }
                )
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pupil in Model.pupils)
        {
            <tr>
                <td>@pupil.FirstName</td>
                <td>@pupil.LastName</td>
                <td>@((SchoolManager.Models.PupilModel.Sexes)pupil.Sex)</td>
                <td>@pupil.BirthdayDate.ToShortDateString()</td>
                <td>
                    @Html.ActionLink(
                        linkText: pupil.TutorName,
                        actionName: "Read",
                        controllerName: "Tutor",
                        routeValues: new
                          {
                              id = @pupil.Tutor_Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: pupil.ClassroomTitle,
                        actionName: "Read",
                        controllerName: "Classroom",
                        routeValues: new
                          {
                              id = @pupil.Classroom_Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: pupil.LevelTitle,
                        actionName: "Read",
                        controllerName: "Level",
                        routeValues: new
                          {
                              area = "Administration",
                              id = @pupil.Level_Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: "See",
                        actionName: "Read",
                        controllerName: "Pupil",
                        routeValues: new
                          {
                              id = @pupil.Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: "Edit",
                        actionName: "Edit",
                        controllerName: "Pupil",
                        routeValues: new
                          {
                              id = @pupil.Id
                          },
                        htmlAttributes: new
                         {
                             target = "_blank",
                         }
                    )
                </td>
            </tr>
        }
    </tbody>
</table>