Models/Pupil.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupil
    {
        public Pupil()
        {
            this.Results = new HashSet<Result>();
        }
    
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public short Sex { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public short State { get; set; }
        public System.Guid Tutor_Id { get; set; }
        public System.Guid Classroom_Id { get; set; }
        public System.Guid Level_Id { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Level Level { get; set; }
        public virtual Tutor Tutor { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}

Areas/ClassManagement/Controllers/PupilController.cs
using OfficeOpenXml;
using OfficeOpenXml.Style;
using SchoolManager.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManager.Areas.ClassManagement.Controllers
{
    public class PupilController : Controller
    {

        public void setViewData()
        {
            using (var entity = new Entities())
            {
                LevelRepository levelRepo = new LevelRepository(entity);
                TutorRepository tutorRepo = new TutorRepository(entity);
                ClassroomRepository classroomRepo = new ClassroomRepository(entity);
                var levels = levelRepo.All().Select(u => new LevelModel
                {
                    Id = u.Id,
                    Title = u.Title,
                    CycleName = u.Cycle.Title
                }).ToList();
                ViewData["levels"] = levels;
                var classrooms = classroomRepo.All().Select(c => new ClassroomModel
                {
                    Id = c.Id,
                    Title = c.Title,
                    User_Name = c.User.FirstName + " " + c.User.LastName,
                    Year1 = c.Year.Year1,
                    Establishment_Name = c.Establishment.Name
                }).ToList();
                ViewData["classrooms"] = classrooms;
                var tutors = tutorRepo.All().Select(t => new TutorModel
                {
                    Id = t.Id,
                    FirstName = t.FirstName,
                    LastName = t.LastName
                }).ToList();
                ViewData["tutors"] = tutors;
            }
        }
        

        public void convertPupilModelToPupil(PupilModel pupil, Pupil p)
        {
            p.Id = pupil.Id;
            p.LastName = pupil.LastName;
            p.FirstName = pupil.FirstName;
            p.Classroom_Id = pupil.Classroom_Id;
            p.Sex = pupil.Sex;
            p.State = 1;
            p.BirthdayDate = pupil.BirthdayDate;
            p.Tutor_Id = pupil.Tutor_Id;
            p.Level_Id = pupil.Level_Id;
            p.Classroom_Id = pupil.Classroom_Id;
        }

        public ActionResult Index()
        {
            using ( var entity = new Entities() )
            {
                var pupilRepo = new PupilRepository(entity);
                List<PupilModel> pupils = pupilRepo.All().Select(p => new PupilModel
                {
                    Id = p.Id,
                    FirstName = p.FirstName,
                    LastName = p.LastName,
                    Sex = p.Sex,
                    BirthdayDate = p.BirthdayDate,
                    State = p.State,
                    Tutor_Id = p.Tutor_Id,
                    Classroom_Id = p.Classroom_Id,
                    Level_Id = p.Level_Id,
                    TutorName = p.Tutor.FirstName + " " + p.Tutor.LastName,
                    LevelTitle = p.Level.Title,
                    ClassroomTitle = p.Classroom.Title
                }).ToList();
                return View(pupils);
            }
        }

        public ActionResult Read(Guid id)
        {
            using (var entity = new Entities())
            {
                var pupilRepo = new PupilRepository(entity);
                PupilModel pupil = pupilRepo.getById(id).Select(p => new PupilModel
                {
                    Id = p.Id,
                    FirstName = p.FirstName,
                    LastName = p.LastName,
                    Sex = p.Sex,
                    BirthdayDate = p.BirthdayDate,
                    State = p.State,
                    Tutor_Id = p.Tutor_Id,
                    Classroom_Id = p.Classroom_Id,
                    Level_Id = p.Level_Id,
                    TutorName = p.Tutor.FirstName + " " + p.Tutor.LastName,
                    LevelTitle = p.Level.Title,
                    ClassroomTitle = p.Classroom.Title
                }).First();
                var resultRepo = new ResultRepository(entity);
                List<ResultModel> results = resultRepo.getByPupil(id).Select(r => new ResultModel {
                    Id = r.Id,
                    Note = r.Note,
                    Evaluation_Id = r.Evaluation.Id,
                    EvaluationTotalPoint = r.Evaluation.TotalPoint,
                    EvaluationDate = r.Evaluation.Date
                }).ToList();
                pupil.resultats = results;
                return View(pupil);
            }
        }

        [HttpGet]
        public ActionResult Create(Guid? Level_Id, Guid? Tutor_Id, Guid? Classroom_Id)
        {
            using (var entity = new Entities())
            {
                PupilModel pupil = new PupilModel();
                if (Level_Id.HasValue)
                {
                    pupil.Level_Id = (Guid) Level_Id;
                }
                if (Tutor_Id.HasValue)
                {
                    pupil.Tutor_Id = (Guid)Tutor_Id;
                }
                if (Classroom_Id.HasValue)
                {
                    pupil.Classroom_Id = (Guid)Classroom_Id;
                }
                setViewData();
                return View(pupil);
            }
        }

        [HttpPost]
        public ActionResult Create(PupilModel pupil)
        {
            if (ModelState.IsValid)
            {
                using (var entity = new Entities())
                {
                    PupilRepository repo = new PupilRepository(entity);
                    pupil.Id = Guid.NewGuid();
                    Pupil p = new Pupil();
                    convertPupilModelToPupil(pupil, p);
                    repo.Add(p);
                    repo.Save();
                    return RedirectToAction("Read", new { id = pupil.Id });
                }

            }
            else
            {
                setViewData();
                return View(pupil);
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            using (var entity = new Entities())
            {
                PupilRepository pupilRepo = new PupilRepository(entity);
                LevelRepository levelRepo = new LevelRepository(entity);
                TutorRepository tutorRepo = new TutorRepository(entity);
                ClassroomRepository classroomRepo = new ClassroomRepository(entity);
                PupilModel pupil = pupilRepo.getById(id).Select(p => new PupilModel
                {
                    Id = p.Id,
                    FirstName = p.FirstName,
                    LastName = p.LastName,
                    Sex = p.Sex,
                    BirthdayDate = p.BirthdayDate,
                    State = p.State,
                    Tutor_Id = p.Tutor_Id,
                    Classroom_Id = p.Classroom_Id,
                    Level_Id = p.Level_Id,
                    TutorName = p.Tutor.FirstName + " " + p.Tutor.LastName,
                    LevelTitle = p.Level.Title,
                    ClassroomTitle = p.Classroom.Title
                }).First();
                setViewData();
                return View(pupil);
            }
        }

        [HttpPost]
        public ActionResult Edit(PupilModel pupil)
        {
            if (ModelState.IsValid)
            {
                using (var entity = new Entities())
                {
                    PupilRepository repo = new PupilRepository(entity);
                    Pupil p = repo.getById(pupil.Id).First();
                    convertPupilModelToPupil(pupil, p);
                    repo.Save();
                    return RedirectToAction("Read", new { id = pupil.Id });
                }

            }
            else
            {
                setViewData();
                return View(pupil);
            }
        }

        [HttpPost]
        public ActionResult Search(string query)
        {
            using(var entity = new Entities()) 
            {
                String[] results = query.Split(new Char[] { ' ', ',' });
                var repo = new PupilRepository(entity);
                var pupils = repo.Search(results).Select(p => new PupilModel
                {
                    Id = p.Id,
                    FirstName = p.FirstName,
                    LastName = p.LastName,
                    Sex = p.Sex,
                    BirthdayDate = p.BirthdayDate,
                    State = p.State,
                    Tutor_Id = p.Tutor_Id,
                    Classroom_Id = p.Classroom_Id,
                    Level_Id = p.Level_Id,
                    TutorName = p.Tutor.FirstName + " " + p.Tutor.LastName,
                    LevelTitle = p.Level.Title,
                    ClassroomTitle = p.Classroom.Title
                }).ToList();
                    
                return PartialView("~/Areas/ClassManagement/Views/Shared/_PupilResults.cshtml", pupils);
            }
        }

        [HttpGet]
        public void GetPupils()
        {
            using (var entity = new Entities())
            {
                PupilRepository pupilRepo = new PupilRepository(entity);
                List<PupilModel> pupils = pupilRepo.All().Select(p => new PupilModel
                {
                    Id = p.Id,
                    FirstName = p.FirstName,
                    LastName = p.LastName,
                    Sex = p.Sex,
                    BirthdayDate = p.BirthdayDate,
                    State = p.State,
                    Tutor_Id = p.Tutor_Id,
                    Classroom_Id = p.Classroom_Id,
                    Level_Id = p.Level_Id,
                    TutorName = p.Tutor.FirstName + " " + p.Tutor.LastName,
                    LevelTitle = p.Level.Title,
                    ClassroomTitle = p.Classroom.Title
                }).ToList();
                using (ExcelPackage pck = new ExcelPackage())
                {
                    //Create the worksheet
                    ExcelWorksheet ws = pck.Workbook.Worksheets.Add("Pupils");

Areas/ClassManagement/Views/Pupil/Create.cshtml
@model SchoolManager.Models.PupilModel
@{
    ViewBag.Title = "Create - Pupil";
    var tutors = (List<SchoolManager.Models.TutorModel>)ViewData["tutors"];
    var classrooms = (List<SchoolManager.Models.ClassroomModel>)ViewData["classrooms"];
    var levels = (List<SchoolManager.Models.LevelModel>)ViewData["levels"];
    var date = Model.BirthdayDate.ToString("yyyy-MM-dd");
}

<h2>New Pupil</h2>
@{Html.BeginForm("Create", "Pupil", FormMethod.Post, new { @class = "form-horizontal" });}
@Html.HiddenFor(p => p.Id)

<div class="form-group @if (!ViewData.ModelState.IsValidField("FirstName")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.FirstName, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.FirstName, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.FirstName, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>


<div class="form-group @if (!ViewData.ModelState.IsValidField("LastName")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.LastName, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.LastName, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.LastName, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>


<div class="form-group">
    <label class="col-sm-2 control-label">Sex</label>
    <div class="col-sm-10">
        <div class="radio">
            <label>
                @if (@Model.Sex == 1)
                {
                    <input checked="checked" type="radio" value="1" id="Sex" name="Sex" />
                }
                else
                {
                    <input type="radio" value="1" id="Sex" name="Sex" />
                }
                Male
            </label>
        </div>
        <div class="radio">
            <label>
                @if (@Model.Sex == 2)
                {
                    <input checked="checked" type="radio" value="2" id="Sex" name="Sex" />
                }
                else
                {
                    <input type="radio" value="1" id="Sex" name="Sex" />
                }
                Female
            </label>
        </div>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Birthday date</label>
    <div class="col-sm-10">
        <input type="date" class="form-control ui-datepicker" placeholder="Birthday date" id="BirthdayDate" name="BirthdayDate" value="@date" />
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Level</label>
    <div class="col-sm-10">
        <select class="form-control" id="Level_Id" name="Level_Id">
            @foreach (var level in levels)
            {
                if (@Model.Level_Id.Equals(level.Id))
                {
                    <option selected="selected" value="@level.Id">@level.Title | @level.CycleName</option>
                }
                else
                {
                    <option value="@level.Id">@level.Title | @level.CycleName</option>
                }

            }
        </select>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Tutor</label>
    <div class="col-sm-10">
        <select class="form-control" id="Tutor_Id" name="Tutor_Id">
            @foreach (var tutor in tutors)
            {
                if (Model.Tutor_Id.Equals(tutor.Id))
                {
                    <option selected="selected" value="@tutor.Id">@tutor.FirstName @tutor.LastName</option>
                }
                else
                {
                    <option value="@tutor.Id">@tutor.FirstName @tutor.LastName</option>
                }
            }
        </select>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Classroom</label>
    <div class="col-sm-10">
        <select class="form-control" id="Classroom_Id" name="Classroom_Id">
            @foreach (var classroom in classrooms)
            {
                if (Model.Classroom_Id.Equals(classroom.Id))
                {
                    <option selected="selected" value="@classroom.Id">@classroom.Title | @classroom.Establishment_Name | @classroom.User_Name | @classroom.Year1.ToString()</option>
                }
                else
                {
                    <option value="@classroom.Id">@classroom.Title | @classroom.Establishment_Name | @classroom.User_Name | @classroom.Year1.ToString()</option>
                }
            }
        </select>
        </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</div>
@{Html.EndForm();}

<!-- Script pour support Firefox -->
<script src="http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js"></script>
<!-- polyfiller file to detect and load polyfills -->
<script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
<script>
    webshims.setOptions('waitReady', false);
    webshims.setOptions('forms-ext', { types: 'date' });
    webshims.polyfill('forms forms-ext');
</script>

Areas/ClassManagement/Views/Pupil/Edit.cshtml
@model SchoolManager.Models.PupilModel
@{
    ViewBag.Title = "Create - Pupil";
    var tutors = (List<SchoolManager.Models.TutorModel>)ViewData["tutors"];
    var classrooms = (List<SchoolManager.Models.ClassroomModel>)ViewData["classrooms"];
    var levels = (List<SchoolManager.Models.LevelModel>)ViewData["levels"];
    var date = Model.BirthdayDate.ToString("yyyy-MM-dd");
}

<h2>Edit Pupil</h2>
@{Html.BeginForm("Edit", "Pupil", FormMethod.Post, new { @class = "form-horizontal" });}
@Html.HiddenFor(p => p.Id)

<div class="form-group @if (!ViewData.ModelState.IsValidField("FirstName")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.FirstName, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.FirstName, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.FirstName, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>


<div class="form-group @if (!ViewData.ModelState.IsValidField("LastName")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.LastName, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.LastName, new { @class = "form-control" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.LastName, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>


<div class="form-group">
    <label class="col-sm-2 control-label">Sex</label>
    <div class="col-sm-10">
        <div class="radio">
            <label>
                @if (@Model.Sex == 1)
                {
                    <input checked="checked" type="radio" value="1" id="Sex" name="Sex" />
                }
                else
                {
                    <input type="radio" value="1" id="Sex" name="Sex" />
                }
                Male
            </label>
        </div>
        <div class="radio">
            <label>
                @if (@Model.Sex == 2)
                {
                    <input checked="checked" type="radio" value="2" id="Sex" name="Sex" />
                }
                else
                {
                    <input type="radio" value="1" id="Sex" name="Sex" />
                }
                Female
            </label>
        </div>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Birthday date</label>
    <div class="col-sm-10">
        <input type="date" class="form-control ui-datepicker" placeholder="Birthday date" id="BirthdayDate" name="BirthdayDate" value="@date"/>
    </div>
</div>

<div class="form-group">
    <label class="col-sm-2 control-label">Level</label>
    <div class="col-sm-10">
        <select class="form-control" id="Level_Id" name="Level_Id">
            @foreach (var level in levels)
            {
                if (@Model.Level_Id.Equals(level.Id))
                {
                    <option selected="selected" value="@level.Id">@level.Title | @level.CycleName</option>
                }
                else
                {
                    <option value="@level.Id">@level.Title | @level.CycleName</option>
                }

            }
        </select>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Tutor</label>
    <div class="col-sm-10">
        <select class="form-control" id="Tutor_Id" name="Tutor_Id">
            @foreach (var tutor in tutors)
            {
                if (Model.Tutor_Id.Equals(tutor.Id))
                {
                    <option selected="selected" value="@tutor.Id">@tutor.FirstName @tutor.LastName</option>
                }
                else
                {
                    <option value="@tutor.Id">@tutor.FirstName @tutor.LastName</option>
                }
            }
        </select>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Classroom</label>
    <div class="col-sm-10">
        <select class="form-control" id="Classroom_Id" name="Classroom_Id">
            @foreach (var classroom in classrooms)
            {
                if (Model.Classroom_Id.Equals(classroom.Id))
                {
                    <option selected="selected" value="@classroom.Id">@classroom.Title | @classroom.Establishment_Name | @classroom.User_Name | @classroom.Year1.ToString()</option>
                }
                else
                {
                    <option value="@classroom.Id">@classroom.Title | @classroom.Establishment_Name | @classroom.User_Name | @classroom.Year1.ToString()</option>
                }
            }
        </select>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Edit" class="btn btn-primary" />
    </div>
</div>
        @{Html.EndForm();}

        <!-- Script pour support Firefox -->
        <script src="http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js"></script>
        <!-- polyfiller file to detect and load polyfills -->
        <script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
        <script>
            webshims.setOptions('waitReady', false);
            webshims.setOptions('forms-ext', { types: 'date' });
            webshims.polyfill('forms forms-ext');
        </script>

Areas/ClassManagement/Views/Pupil/Index.cshtml
@model List<SchoolManager.Models.PupilModel>
@{
    ViewBag.Title = "Pupils";
}

<h2>Pupils</h2>
<div id="search">
    @using (Ajax.BeginForm("Search", "Pupil",
        new AjaxOptions
        {
            UpdateTargetId = "PupilsArray",
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
        }, new { @class = "form-group" }))
    {
        <div class="input-group">
            <input type="text" name="query" class="form-control" placeholder="Search..." />
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-search"></i>
            </span>
        </div>
    }
</div>
<div id="PupilsArray">
    @Html.Partial("~/Areas/ClassManagement/Views/Shared/_PupilResults.cshtml", @Model)
</div>

Areas/ClassManagement/Views/Pupil/Read.cshtml
@model SchoolManager.Models.PupilModel
@{
    ViewBag.Title = "Pupil";
}

<h2>Pupil @Model.FirstName @Model.LastName</h2>

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Sex</th>
            <th>Birthday Date</th>
            <th>Tutor</th>
            <th>Classroom</th>
            <th>Level</th>
        </tr>
    </thead>
    <tbody>
    <tr>
        <td>@Model.FirstName</td>
        <td>@Model.LastName</td>
        <td>@((SchoolManager.Models.PupilModel.Sexes)Model.Sex)</td>
        <td>@Model.BirthdayDate.ToShortDateString()</td>
        <td>
            @Html.ActionLink(
                linkText: Model.TutorName,
                actionName: "Read",
                controllerName: "Tutor",
                routeValues: new
                    {
                        id = @Model.Tutor_Id
                    },
                htmlAttributes: new
                    {
                        target = "_blank",
                    }
            )
        </td>
        <td>
            @Html.ActionLink(
                linkText: Model.ClassroomTitle,
                actionName: "Read",
                controllerName: "Classroom",
                routeValues: new
                    {
                        id = @Model.Classroom_Id
                    },
                htmlAttributes: new
                    {
                        target = "_blank",
                    }
            )
        </td>
        <td>
            @Html.ActionLink(
                linkText: Model.LevelTitle,
                actionName: "Read",
                controllerName: "Level",
                routeValues: new
                    {
                        area = "Administration",
                        id = @Model.Level_Id
                    },
                htmlAttributes: new
                    {
                        target = "_blank",
                    }
            )
        </td>
        <td>
            @Html.ActionLink(
                linkText: "Edit",
                actionName: "Edit",
                controllerName: "Pupil",
                routeValues: new
                    {
                        id = @Model.Id
                    },
                htmlAttributes: new
                    {
                        target = "_blank",
                    }
            )
        </td>
        </tr>
    </tbody>
</table>


<h2>Results</h2>
<table class="table">
    <thead>
        <tr>
            <th>Date</th>
            <th>Note</th>
            <th>Total point</th>
        </tr>
    </thead>
    @foreach (var resultat in @Model.resultats)
    { 
        <tr>
            <td>@resultat.EvaluationDate.ToShortDateString()</td>
            <td>@resultat.Note</td>
            <td>@resultat.EvaluationTotalPoint</td>
        </tr>
    }
</table>