Models/Evaluation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluation
    {
        public Evaluation()
        {
            this.Results = new HashSet<Result>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Classroom_Id { get; set; }
        public System.Guid User_Id { get; set; }
        public System.Guid Period_Id { get; set; }
        public System.DateTime Date { get; set; }
        public int TotalPoint { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Period Period { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}

Areas/ClassManagement/Controllers/EvaluationController.cs
using SchoolManager.Areas.ClassManagement.Models;
using SchoolManager.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolManager.Areas.ClassManagement.Controllers
{
    public class EvaluationController : Controller
    {

        private void setViewData()
        {
            using (var entity = new Entities())
            {
                ClassroomRepository classroomRepo = new ClassroomRepository(entity);
                PeriodRepository periodRepo = new PeriodRepository(entity);
                ViewData["classrooms"] = classroomRepo.All().Select(c => new ClassroomModel
                {
                    Id = c.Id,
                    Title = c.Title,
                    User_Id = c.User.Id,
                    User_Name = c.User.FirstName + " " + c.User.LastName,
                    Year1 = c.Year.Year1,
                    Establishment_Name = c.Establishment.Name
                }).ToList();
                ViewData["periods"] = periodRepo.All().Select(p => new PeriodModel
                {
                    Id = p.Id,
                    Begin = p.Begin,
                    End = p.End
                }).ToList();
            }
        }

        private void convertResultModelToResult(ResultModel result, Result r)
        {
            r.Id = result.Id;
            r.Evaluation_Id = result.Evaluation_Id;
            r.Note = result.Note;
            r.Pupil_Id = result.Pupil_Id;
        }
        
        public void convertEvaluationModelToEvaluation(EvaluationModel evaluation, Evaluation e)
        {
            e.Id = evaluation.Id;
            e.Classroom_Id = evaluation.Classroom_Id;
            e.Date = evaluation.Date;
            e.TotalPoint = evaluation.TotalPoint;
            e.User_Id = evaluation.User_Id;
            e.Period_Id = evaluation.Period_Id;
        }
        
        //
        // GET: /ClassManagement/Evaluation/

        public ActionResult Index()
        {
            using (var entity = new Entities())
            {
                var evalRepo = new EvaluationRepository(entity);
                List<EvaluationModel> evals = evalRepo.All().Select(e => new EvaluationModel
                {
                    Id = e.Id,
                    Classroom_Id = e.Classroom_Id,
                    Classroom_Title = e.Classroom.Title,
                    User_Id = e.User_Id,
                    User_Name = e.User.FirstName + " " + e.User.LastName,
                    Period_Id = e.Period_Id,
                    Period_Begin = e.Period.Begin,
                    Period_End = e.Period.End,
                    Year1 = e.Period.Year.Year1,
                    Year_Id = e.Period.Year_Id,
                    Date = e.Date,
                    TotalPoint = e.TotalPoint,
                    Results_Number = e.Results.Count
                }).ToList();
                return View(evals);
            }
        }

        [HttpGet]
        public ActionResult Create(Guid? Period_Id, Guid? Classroom_Id)
        {
            using (var entity = new Entities()) {
                EvaluationModel eval = new EvaluationModel();
                ClassroomRepository classroomRepo = new ClassroomRepository(entity);
                PeriodRepository periodRepo = new PeriodRepository(entity);
                UserRepository userRepo = new UserRepository(entity);

                if (Period_Id.HasValue)
                {
                    eval.Period_Id = (Guid) Period_Id;
                }

                if (Classroom_Id.HasValue)
                {
                    eval.Classroom_Id = (Guid)Classroom_Id;
                }
                setViewData();
                return View(eval);
            }
        }

        [HttpPost]
        public ActionResult Create(EvaluationModel eval)
        {
            if (ModelState.IsValid)
            {
                using (var entity = new Entities())
                {
                    EvaluationRepository evaluationRepo = new EvaluationRepository(entity);
                    ClassroomRepository classroomRepo = new ClassroomRepository(entity);
                    UserRepository userRepo = new UserRepository(entity);
                    eval.Id = Guid.NewGuid();
                    eval.User_Id = classroomRepo.getById(eval.Classroom_Id).First().User_Id;
                    Evaluation e = new Evaluation();
                    convertEvaluationModelToEvaluation(eval, e);
                    evaluationRepo.Add(e);
                    evaluationRepo.Save();
                    return RedirectToAction("Read", new { @id = eval.Id });
                }
            }
            setViewData();
            return View(eval);
        }

        [HttpGet]
        public ActionResult AddResults(Guid id)
        {
            using (var entity = new Entities()) {
                PupilRepository pupilRepo = new PupilRepository(entity);

                EvaluationRepository evalRepo = new EvaluationRepository(entity);
                EvaluationModel eval = evalRepo.getById(id).Select(e => new EvaluationModel
                {
                    Id = e.Id,
                    Classroom_Id = e.Classroom_Id,
                    Classroom_Title = e.Classroom.Title,
                    User_Id = e.User_Id,
                    User_Name = e.User.FirstName + " " + e.User.LastName,
                    Period_Id = e.Period_Id,
                    Period_Begin = e.Period.Begin,
                    Period_End = e.Period.End,
                    Year1 = e.Period.Year.Year1,
                    Year_Id = e.Period.Year_Id,
                    Date = e.Date,
                    TotalPoint = e.TotalPoint,
                    Results_Number = e.Results.Count
                    
                }).First();
                List<PupilModel> pupils = pupilRepo.getByClassroom(eval.Classroom_Id).Select(p => new PupilModel {
                    Id = p.Id,
                    FirstName = p.FirstName,
                    LastName = p.LastName,
                    Sex = p.Sex,
                    BirthdayDate = p.BirthdayDate,
                    State = p.State,
                    Tutor_Id = p.Tutor_Id,
                    TutorName = p.Tutor.FirstName + " " + p.Tutor.LastName,
                    Classroom_Id = p.Classroom_Id,
                    ClassroomTitle = p.Classroom.Title,
                    Level_Id = p.Level_Id,
                    LevelTitle = p.Level.Title
                }).ToList();
                ViewData["pupils"] = pupils;
                ViewData["evaluation"] = eval;
                List<ResultModel> results = new List<ResultModel>();
                foreach (var pupil in pupils)
                {
                    results.Add(new ResultModel());
                }
                return View(results);
            }
        }

        [HttpPost]
        public ActionResult AddResults(List<ResultModel> results)
        {
            using (var entity = new Entities()) {
                var resultRepo = new ResultRepository(entity);
                foreach (var result in results)
                {
                    result.Id = Guid.NewGuid();
                    Result r = new Result();
                    convertResultModelToResult(result, r);
                    resultRepo.Add(r);
                }
                resultRepo.Save();

            }
            return RedirectToAction("Read", new { id = results[0].Evaluation_Id });
        }

        [HttpGet]
        public ActionResult Read(Guid id)
        {
            using (var entity = new Entities())
            {
                ResultRepository resultRepo = new ResultRepository(entity);
                EvaluationRepository evalRepo = new EvaluationRepository(entity);
                EvaluationModel eval = evalRepo.getById(id).Select(e => new EvaluationModel
                {
                    Id = e.Id,
                    Classroom_Id = e.Classroom_Id,
                    Classroom_Title = e.Classroom.Title,
                    User_Id = e.User_Id,
                    User_Name = e.User.FirstName + " " + e.User.LastName,
                    Period_Id = e.Period_Id,
                    Period_Begin = e.Period.Begin,
                    Period_End = e.Period.End,
                    Year1 = e.Period.Year.Year1,
                    Year_Id = e.Period.Year_Id,
                    Date = e.Date,
                    TotalPoint = e.TotalPoint,
                    Results_Number = e.Results.Count
                }).First();
                ViewData["results"] = resultRepo.getByEvaluation(id).Select(r => new ResultModel
                {
                    Id = r.Id,
                    Note = r.Note,
                    Evaluation_Id = r.Evaluation.Id,
                    EvaluationTotalPoint = r.Evaluation.TotalPoint,
                    EvaluationDate = r.Evaluation.Date,
                    Pupil_Id = r.Pupil_Id,
                    Pupil_Name = r.Pupil.FirstName + " " + r.Pupil.LastName
                }).ToList();
                return View(eval);
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            using(var entity = new Entities()) {
                EvaluationRepository evalRepo = new EvaluationRepository(entity);
                ResultRepository resultRepo = new ResultRepository(entity);
                EvaluationModel eval = evalRepo.getById(id).Select(e => new EvaluationModel
                {
                    Id = e.Id,
                    Classroom_Id = e.Classroom_Id,
                    Classroom_Title = e.Classroom.Title,
                    User_Id = e.User_Id,
                    User_Name = e.User.FirstName + " " + e.User.LastName,
                    Period_Id = e.Period_Id,
                    Period_Begin = e.Period.Begin,
                    Period_End = e.Period.End,
                    Year1 = e.Period.Year.Year1,

Areas/ClassManagement/Views/Evaluation/AddResults.cshtml
@model List<SchoolManager.Models.ResultModel>
@{
    ViewBag.Title = "Add Results";
    var eval = (SchoolManager.Models.EvaluationModel)ViewData["evaluation"];
    var pupils = (List<SchoolManager.Models.PupilModel>)ViewData["pupils"];
}

<h2>Add Results</h2>
<table class="table">
    <thead>
        <tr>
            <th>Year</th>
            <th>Period</th>
            <th>Classroom</th>
            <th>User</th>

            <th>Date</th>
            <th>TotalPoint</th>
        </tr>
    </thead>
    <tbody>
        <tr>

            <td>
                @Html.ActionLink(
                linkText: eval.Year1.ToString(),
                actionName: "Read",
                controllerName: "Year",
                routeValues: new
                {
                    area = "Administration",
                    id = eval.Year_Id
                },
                htmlAttributes: new
                {
                    @class = "",
                    target = "_blank",
                }
            )
            </td>
            <td>
                @Html.ActionLink(
                linkText: eval.Period_Begin.ToShortDateString() + " - " + eval.Period_End.ToShortDateString(),
                actionName: "Read",
                controllerName: "Period",
                routeValues: new
                {
                    area = "Administration",
                    id = eval.Period_Id
                },
                htmlAttributes: new
                {
                    @class = "",
                    target = "_blank",
                }
            )
            </td>
            <td>
                @Html.ActionLink(
                linkText: eval.Classroom_Title,
                actionName: "Read",
                controllerName: "Classroom",
                routeValues: new
                {
                    id = eval.Classroom_Id
                },
                htmlAttributes: new
                {
                    @class = "",
                    target = "_blank",
                }
            )
        </td>
        <td>@eval.User_Name</td>

        <td>@eval.Date.ToShortDateString()</td>
        <td>
            @eval.TotalPoint
        </td>
        </tr>
    </tbody>
</table>

@{Html.BeginForm("AddResults", "Evaluation", FormMethod.Post, new { @class = "form-horizontal" });}
<div class="form-group">
     <div class="col-sm-offset-2 col-sm-8">
        <table class="table">
            <thead>
                <tr class="row">
                    <th class="col-sm-6">Pupil</th>
                    <th class="col-sm-6">Result</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < pupils.Count; i++)
                {
                    <tr class="row">
                        @Html.HiddenFor(r => r[i].Pupil_Id, new { Value = pupils[i].Id })
                        @Html.HiddenFor(r => r[i].Evaluation_Id, new { Value = eval.Id })
                        <td class="col-sm-6">@pupils[i].FirstName @pupils[i].LastName</td>
                        <td class="col-sm-6">@Html.TextBoxFor(r => r[i].Note, new { type = "number", @class = "form-control", min = "0", max = eval.TotalPoint })</td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Add Results" class="btn btn-primary" />
    </div>
</div>
@{Html.EndForm();}

Areas/ClassManagement/Views/Evaluation/Create.cshtml
@model SchoolManager.Models.EvaluationModel
@{
    ViewBag.Title = "Create - Evaluation";
    List<SchoolManager.Models.ClassroomModel> classrooms = (List<SchoolManager.Models.ClassroomModel>)ViewData["classrooms"];
    List<SchoolManager.Models.PeriodModel> periods = (List<SchoolManager.Models.PeriodModel>)ViewData["periods"];
    var date = Model.Date.ToString("yyyy-MM-dd"); 
}

<h2>Create new Evaluation</h2>
@{Html.BeginForm("Create", "Evaluation", FormMethod.Post, new { @class = "form-horizontal" });}
@Html.HiddenFor(p => p.Id)

<div class="form-group @if (!ViewData.ModelState.IsValidField("Date")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Date, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                <input type="date" class="form-control" placeholder="Date" id="Date" name="Date" value="@date" />
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Date, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>



<div class="form-group @if (!ViewData.ModelState.IsValidField("TotalPoint")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.TotalPoint, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.TotalPoint, new { @class = "form-control", @type = "number" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.TotalPoint, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>


<div class="form-group">
    <label class="col-sm-2 control-label">Period</label>
    <div class="col-sm-10">
        <select class="form-control" id="Period_Id" name="Period_Id">
            @foreach (var period in periods)
            {
                if (period.Id == @Model.Period_Id)
                {
                    <option selected="selected" value="@period.Id">@period.Begin.ToShortDateString() - @period.End.ToShortDateString()</option>
                }
                else
                {
                    <option value="@period.Id">@period.Begin.ToShortDateString() - @period.End.ToShortDateString()</option>
                }
            }
        </select>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Classroom</label>
    <div class="col-sm-10">
        <select class="form-control" id="Classroom_Id" name="Classroom_Id">
            @foreach (var classroom in classrooms)
            {
                if (classroom.Id == @Model.Classroom_Id)
                {
                    <option selected="selected" value="@classroom.Id">@classroom.Title | @classroom.Establishment_Name | @classroom.User_Name | @classroom.Year1.ToString()</option>
                }
                else
                {
                    <option value="@classroom.Id">@classroom.Title | @classroom.Establishment_Name | @classroom.User_Name | @classroom.Year1.ToString()</option>
                }
            }
        </select>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</div>
@{Html.EndForm();}

<!-- Script pour support Firefox -->
<script src="http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js"></script>
<!-- polyfiller file to detect and load polyfills -->
<script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
<script>
    webshims.setOptions('waitReady', false);
    webshims.setOptions('forms-ext', { types: 'date' });
    webshims.polyfill('forms forms-ext');
</script>

Areas/ClassManagement/Views/Evaluation/Edit.cshtml
@model SchoolManager.Models.EvaluationModel
@{
    ViewBag.Title = "Edit";
    List<SchoolManager.Models.ClassroomModel> classrooms = (List<SchoolManager.Models.ClassroomModel>)ViewData["classrooms"];
    List<SchoolManager.Models.PeriodModel> periods = (List<SchoolManager.Models.PeriodModel>)ViewData["periods"];
    List<SchoolManager.Models.ResultModel> results = (List<SchoolManager.Models.ResultModel>)ViewData["results"];
    var date = Model.Date.ToString("yyyy-MM-dd"); 
}

<h2>Edit - Evaluation</h2>

@{Html.BeginForm("Edit", "Evaluation", FormMethod.Post, new { @class = "form-horizontal" });}
@Html.HiddenFor(p => p.Id)

<div class="form-group @if (!ViewData.ModelState.IsValidField("Date")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.Date, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                <input type="date" class="form-control" placeholder="Date" id="Date" name="Date" value="@date" />
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.Date, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>



<div class="form-group @if (!ViewData.ModelState.IsValidField("TotalPoint")) { @Html.Raw("has-error") ; }">
    @Html.LabelFor(t => t.TotalPoint, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-10 controls">
        <div class="row">
            <div class="col-sm-8">
                @Html.TextBoxFor(t => t.TotalPoint, new { @class = "form-control", @type = "number" })
            </div>
            <div class="col-sm-4">
                @Html.ValidationMessageFor(t => t.TotalPoint, null, new { @class = "help-block" })
            </div>
        </div>
    </div>
</div>


<div class="form-group">
    <label class="col-sm-2 control-label">Period</label>
    <div class="col-sm-10">
        <select class="form-control" id="Period_Id" name="Period_Id">
            @foreach (var period in periods)
            {
                if (period.Id == @Model.Period_Id)
                {
                    <option selected="selected" value="@period.Id">@period.Begin.ToShortDateString() - @period.End.ToShortDateString()</option>
                }
                else
                {
                    <option value="@period.Id">@period.Begin.ToShortDateString() - @period.End.ToShortDateString()</option>
                }
            }
        </select>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-2 control-label">Classroom</label>
    <div class="col-sm-10">
        <select class="form-control" id="Classroom_Id" name="Classroom_Id">
            @foreach (var classroom in classrooms)
            {
                if (classroom.Id == @Model.Classroom_Id)
                {
                    <option selected="selected" value="@classroom.Id">@classroom.Title | @classroom.Establishment_Name | @classroom.User_Name | @classroom.Year1.ToString()</option>
                }
                else
                {
                    <option value="@classroom.Id">@classroom.Title | @classroom.Establishment_Name | @classroom.User_Name | @classroom.Year1.ToString()</option>
                }
            }
        </select>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Edit" class="btn btn-primary" />
    </div>
</div>
@{Html.EndForm();}
@{Html.RenderPartial("_EditResults", Model.Results);}




<!-- Script pour support Firefox -->
<script src="http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js"></script>
<!-- polyfiller file to detect and load polyfills -->
<script src="http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js"></script>
<script>
    webshims.setOptions('waitReady', false);
    webshims.setOptions('forms-ext', { types: 'date' });
    webshims.polyfill('forms forms-ext');
</script>

Areas/ClassManagement/Views/Evaluation/Index.cshtml
@model List<SchoolManager.Models.EvaluationModel>
@{
    ViewBag.Title = "Evaluations";
}

<h2>Evaluations</h2>
<table class="table">
    <thead>
        <tr>
            <th>Year</th>
            <th>Period</th>
            <th>Classroom</th>
            <th>User</th>
            
            <th>Date</th>
            <th>TotalPoint</th>
            <th>
                @Html.ActionLink(
                    linkText: "Add Evaluation",
                    actionName: "Create",
                    controllerName: "Evaluation",
                    routeValues: new
                    {
                    },
                    htmlAttributes: new
                    {
                        @class = "btn btn-default btn-sm",
                    }
                )
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var eval in Model)
        {
            <tr>

                <td>
                    @Html.ActionLink(
                        linkText: eval.Year1.ToString(),
                        actionName: "Read",
                        controllerName: "Year",
                        routeValues: new
                        {
                            area="Administration",
                            id = eval.Year_Id
                        },
                        htmlAttributes: new
                        {
                            @class = "",
                            target = "_blank",
                        }
                    )
            </td>
                <td>
                    @Html.ActionLink(
                        linkText: eval.Period_Begin.ToShortDateString() + " - " + eval.Period_End.ToShortDateString() ,
                        actionName: "Read",
                        controllerName: "Period",
                        routeValues: new
                        {
                            area="Administration",
                            id = eval.Period_Id
                        },
                        htmlAttributes: new
                        {
                            @class = "",
                            target = "_blank",
                        }
                    )
            </td>
                <td>@Html.ActionLink(
                        linkText: eval.Classroom_Title,
                        actionName: "Read",
                        controllerName: "Classroom",
                        routeValues: new
                        {
                            id=eval.Classroom_Id
                        },
                        htmlAttributes: new
                        {
                            @class = "",
                            target = "_blank",
                        }
                    )
                </td>
                <td>@eval.User_Name</td>
                
                <td>@eval.Date.ToShortDateString()</td>
                <td>
                    @eval.TotalPoint
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: "See",
                        actionName: "Read",
                        controllerName: "Evaluation",
                        routeValues: new
                          {
                              id = @eval.Id
                          },
                        htmlAttributes: new
                         {
                             
                         }
                    )
                </td>
                <td>
                    @Html.ActionLink(
                        linkText: "Edit",
                        actionName: "Edit",
                        controllerName: "Evaluation",
                        routeValues: new
                          {
                              id = @eval.Id
                          },
                        htmlAttributes: new
                         {
                             
                         }
                    )
                </td>
                @if (!eval.HasResults) { 
                    <td>
                        @Html.ActionLink(
                            linkText: "Add Results",
                            actionName: "AddResults",
                            controllerName: "Evaluation",
                            routeValues: new
                              {
                                  id = @eval.Id
                              },
                            htmlAttributes: new
                             {
                                 @class="btn btn-default btn-sm",
                                 target = "_blank",
                             }
                        )
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

Areas/ClassManagement/Views/Evaluation/_EditResults.cshtml
@model List<SchoolManager.Models.ResultModel>
@{
    ViewBag.Title = "_EditResults";
}

<h2>Edit Results</h2>
@if (Model.Count != 0) { 
Html.BeginForm("EditResults", "Evaluation", FormMethod.Post, new { @class = "form-horizontal" });
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
        <table class="table">
            <thead>
                <tr class="row">
                    <th class="col-sm-6">Pupil</th>
                    <th class="col-sm-6">Result</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count; i++)
                {
                    <tr class="row">
                        @Html.HiddenFor(r => Model[i].Id)
                        @Html.HiddenFor(r => Model[i].Pupil_Id, new { Value = Model[i].Pupil_Id })
                        @Html.HiddenFor(r => Model[i].Evaluation_Id, new { Value = Model[i].Evaluation_Id })
                        <td class="col-sm-6">@Model[i].Pupil_Name</td>
                        <td class="col-sm-6">@Html.TextBoxFor(r => Model[i].Note, new { type = "number", @class = "form-control", min = "0", max = Model[i].EvaluationTotalPoint });</td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <input type="submit" value="Edit Results" class="btn btn-primary" />
    </div>
</div>
        Html.EndForm();
}
else
{
    <p class="col-sm-offset-1">No results for this evaluation</p>
}